// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: tzero/v1/common/payment_receipt.proto

package common

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PaymentReceipt with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PaymentReceipt) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PaymentReceipt with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PaymentReceiptMultiError,
// or nil if none found.
func (m *PaymentReceipt) ValidateAll() error {
	return m.validate(true)
}

func (m *PaymentReceipt) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Details.(type) {
	case *PaymentReceipt_Sepa:
		if v == nil {
			err := PaymentReceiptValidationError{
				field:  "Details",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetSepa()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PaymentReceiptValidationError{
						field:  "Sepa",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PaymentReceiptValidationError{
						field:  "Sepa",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetSepa()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PaymentReceiptValidationError{
					field:  "Sepa",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *PaymentReceipt_Swift:
		if v == nil {
			err := PaymentReceiptValidationError{
				field:  "Details",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetSwift()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PaymentReceiptValidationError{
						field:  "Swift",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PaymentReceiptValidationError{
						field:  "Swift",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetSwift()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PaymentReceiptValidationError{
					field:  "Swift",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *PaymentReceipt_Stablecoin:
		if v == nil {
			err := PaymentReceiptValidationError{
				field:  "Details",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetStablecoin()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PaymentReceiptValidationError{
						field:  "Stablecoin",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PaymentReceiptValidationError{
						field:  "Stablecoin",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetStablecoin()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PaymentReceiptValidationError{
					field:  "Stablecoin",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return PaymentReceiptMultiError(errors)
	}

	return nil
}

// PaymentReceiptMultiError is an error wrapping multiple validation errors
// returned by PaymentReceipt.ValidateAll() if the designated constraints
// aren't met.
type PaymentReceiptMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PaymentReceiptMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PaymentReceiptMultiError) AllErrors() []error { return m }

// PaymentReceiptValidationError is the validation error returned by
// PaymentReceipt.Validate if the designated constraints aren't met.
type PaymentReceiptValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaymentReceiptValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaymentReceiptValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaymentReceiptValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaymentReceiptValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaymentReceiptValidationError) ErrorName() string { return "PaymentReceiptValidationError" }

// Error satisfies the builtin error interface
func (e PaymentReceiptValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPaymentReceipt.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaymentReceiptValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaymentReceiptValidationError{}

// Validate checks the field values on SepaReceipt with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SepaReceipt) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SepaReceipt with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SepaReceiptMultiError, or
// nil if none found.
func (m *SepaReceipt) ValidateAll() error {
	return m.validate(true)
}

func (m *SepaReceipt) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SepaReceiptMultiError(errors)
	}

	return nil
}

// SepaReceiptMultiError is an error wrapping multiple validation errors
// returned by SepaReceipt.ValidateAll() if the designated constraints aren't met.
type SepaReceiptMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SepaReceiptMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SepaReceiptMultiError) AllErrors() []error { return m }

// SepaReceiptValidationError is the validation error returned by
// SepaReceipt.Validate if the designated constraints aren't met.
type SepaReceiptValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SepaReceiptValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SepaReceiptValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SepaReceiptValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SepaReceiptValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SepaReceiptValidationError) ErrorName() string { return "SepaReceiptValidationError" }

// Error satisfies the builtin error interface
func (e SepaReceiptValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSepaReceipt.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SepaReceiptValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SepaReceiptValidationError{}

// Validate checks the field values on SwiftReceipt with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SwiftReceipt) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SwiftReceipt with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SwiftReceiptMultiError, or
// nil if none found.
func (m *SwiftReceipt) ValidateAll() error {
	return m.validate(true)
}

func (m *SwiftReceipt) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SwiftReceiptMultiError(errors)
	}

	return nil
}

// SwiftReceiptMultiError is an error wrapping multiple validation errors
// returned by SwiftReceipt.ValidateAll() if the designated constraints aren't met.
type SwiftReceiptMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SwiftReceiptMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SwiftReceiptMultiError) AllErrors() []error { return m }

// SwiftReceiptValidationError is the validation error returned by
// SwiftReceipt.Validate if the designated constraints aren't met.
type SwiftReceiptValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SwiftReceiptValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SwiftReceiptValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SwiftReceiptValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SwiftReceiptValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SwiftReceiptValidationError) ErrorName() string { return "SwiftReceiptValidationError" }

// Error satisfies the builtin error interface
func (e SwiftReceiptValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSwiftReceipt.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SwiftReceiptValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SwiftReceiptValidationError{}

// Validate checks the field values on StablecoinReceipt with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *StablecoinReceipt) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StablecoinReceipt with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StablecoinReceiptMultiError, or nil if none found.
func (m *StablecoinReceipt) ValidateAll() error {
	return m.validate(true)
}

func (m *StablecoinReceipt) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TransactionHash

	if len(errors) > 0 {
		return StablecoinReceiptMultiError(errors)
	}

	return nil
}

// StablecoinReceiptMultiError is an error wrapping multiple validation errors
// returned by StablecoinReceipt.ValidateAll() if the designated constraints
// aren't met.
type StablecoinReceiptMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StablecoinReceiptMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StablecoinReceiptMultiError) AllErrors() []error { return m }

// StablecoinReceiptValidationError is the validation error returned by
// StablecoinReceipt.Validate if the designated constraints aren't met.
type StablecoinReceiptValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StablecoinReceiptValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StablecoinReceiptValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StablecoinReceiptValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StablecoinReceiptValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StablecoinReceiptValidationError) ErrorName() string {
	return "StablecoinReceiptValidationError"
}

// Error satisfies the builtin error interface
func (e StablecoinReceiptValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStablecoinReceipt.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StablecoinReceiptValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StablecoinReceiptValidationError{}
